### PR TITLE
Fix for equal? bug #312

### PR DESCRIPTION
**Pull request by dcurrie**
Detect that both lists are circular before calling then equal.

### CODE REVIEW

**Comment by KeenS** [comment]
@dcurrie Thank you. Looks great to me.

**Comment by KeenS** [comment]
Note that this patch isn't complete.
Think such case.

```scheme
(let ((l (list 1 1)))
  (set-cdr! l l)
  (equal? l (make-list 10 1)))
```

However as is said "Done is better than perfect", We accept this patch.

**Comment by KeenS** [comment]
@dcurrie FYI, I added a regression test suite.
https://github.com/picrin-scheme/picrin/blob/master/t/issue/312.scm

**Comment by dcurrie** [comment]
Re: not complete...

I believe my patch gives the correct result for your test (`#f`):

```
e$ chibi-scheme
> (let ((l (list 1 1)))
  (set-cdr! l l)
  (equal? l (make-list 10 1)))
#f
>
e$ larceny -r7rs
Larceny v0.98 "General Ripper" (Mar  7 2015 01:24:18, precise:Posix:unified)
larceny.heap, built on Sat Mar  7 01:25:38 EST 2015

> (let ((l (list 1 1)))
  (set-cdr! l l)
  (equal? l (make-list 10 1)))
#f
> 
e$ picrin
> (let ((l (list 1 1)))
  (set-cdr! l l)
  (equal? l (make-list 10 1)))
#f
> ^D
```

**Comment by KeenS** [comment]
Hmm... Yes, you're right. Maybe I tested under an old binary. Thank you anyway.

**Pull request merged**
