### PR TITLE
Better error message2

### PR DESCRIPTION
**Pull request by KeenS**
rebased.

### CODE REVIEW

**Comment by wasabiz** [comment]
@KeenS 

"for equal to or more than" sounds wired to me. Do you have some alternatives?

**Comment by KeenS** [comment]
>=

**Comment by wasabiz** [comment]
@KeenS 

What would clang show in such the case?

**Comment by KeenS** [comment]
@wasabiz I'm not so familiar with C to write code which use variable length argument.
FYI, when `max` is called with no arguments,  
gauche and sagittarius say "wrong number of arguments (required 1, but got 0)"  
chibi-scheme say "not enough args 0"  

sbcl says "invalid number of arguments: 0"
ccl says "Too few arguments in call to max: 0 arguments provided, at least 1 required."

I prefer ccl way.

**Comment by wasabiz** [comment]
@KeenS 

cool. I prefer ccl, too. how about mixing gauche and ccl, like "(at least 1 required, but got 0)"?

**Comment by KeenS** [comment]
I like it. Then let's change the [other error messages](https://github.com/picrin-scheme/picrin/blob/master/extlib/benz/vm.c#L915).

**Comment by roklein** [comment]
A comment to "for equal to or more than":

Would you perhaps prefer something like:

(%d; at least %d are needed)

or

(%d; %d or more are needed)

or in active voice (alternatives in [|] brackets):  

(%d; you need [at least %d|%d or more])

Thank you very much for your consideration.

**Comment by wasabiz** [comment]
@roklein @KeenS 

Thank you for the suggestion. As you pointed out, it could be much shorter. How about using `for`?

```
wrong number of arguments (1 for at least 2)
```

**Comment by KeenS** [comment]
@wasabiz 
:+1:

**Comment by roklein** [comment]
How about `instead of` instead of both `;` or `for`?

**Comment by wasabiz** [comment]
> How about instead of instead of both ; or for?

That message doesn't make much sense to me. Let's go with 'for'.

**Comment by KeenS** [comment]
I agree with @wasabiz

**Comment by wasabiz** [comment]
@KeenS 

I just changed an error message left untouched in the same way. There are still some messages we haven't started to revise inside pic_get_args. After they all are fixed I think I can merge.

**Comment by wasabiz** [comment]
@KeenS 

Do you think this is ready to use?

**Comment by KeenS** [comment]
@wasabiz Yes.

**Comment by KeenS** [comment]
@wasabiz I noticed proc name was to be fixed. Wait a moment.

**Comment by wasabiz** [comment]
Beautiful :)

**Pull request merged**
