### PR TITLE
Extend test

### PR DESCRIPTION
**Pull request by omasanori**
Add an optional argument ``=`` to use custom comparators.

### CODE REVIEW

**Comment by omasanori** [comment]
Travis seems to decide to ignore me, but it works well. Believe me :-/

**Comment by KeenS** [comment]
FYI there are undergoing project to enchant test, extending to SRFI 64 https://github.com/picrin-scheme/picrin/tree/enchant-test

**Comment by omasanori** [comment]
@KeenS Thank you. So, should #300 be suspended until SRFI 64 is landed?

**Comment by KeenS** [comment]
@omasanori Not at all. When the project arrived, you can fix it then.

**Comment by omasanori** [comment]
I see.

**Pull request merged**
