### PR TITLE
Bytecompile

### PR DESCRIPTION
**Pull request by KeenS**
Implement benz issue 13 (byte compile)
- Unpickling symbol haven't implemented
- (un)pickling ext haven't implemented

How can I implement them?

### CODE REVIEW

**Comment by wasabiz** [comment]
@KeenS 

Symbol support is mandatory to be merged into master. Emitting string-to-symbol alist at the beginning of binary should be the only solution.

**Comment by wasabiz** [comment]
@KeenS 

How about emitting the table as a simple alist?

```
(pickle '(define (id x) x))

=>

byte representation of '(((0 . "define") (1 . "id") (3 . "x")) . (0* (1* 3*) 3*)) is emit,
where N* denotes numeric representation of symbol (to distinguish with fixnum).
```

**Comment by KeenS** [comment]
@wasabiz 
Sounds good. I' ll do it.

**Comment by KeenS** [comment]
@wasabiz 
I noticed [the current byte encoding specification](https://github.com/picrin-scheme/benz/issues/13) doesn't have pair. It is needed not only by above symbol table format but also by procedure definition like `(define (foo a b . rest) ...)`.

We need to redesign the specification!

**Comment by KeenS** [comment]
@wasabiz 
Do you need this patch now?

**Pull request closed without merging**
