### PR TITLE
Fix typo, alerm -> alarm.

### PR DESCRIPTION
**Pull request by omasanori**
This commit also enables some tests to catch more regressions.

### CODE REVIEW

**Comment by wasabiz** [comment]
Thanks for the fix! You can push it to master directly without making a pull request for such a small bugfix. I just meant that it would be better for us to share what you meant to change if it were large (sometimes breaking) changes. Thanks again for many patches, anyways. They all help greatly.

**Comment by omasanori** [comment]
Thank you for your advice. I made a PR for every small fix because I wanted to trigger CI builds before merging into master (I usually test patches only on amd64 GCC), but I'll push to master directly if it is preferred on the project.

**Comment by KeenS** [comment]
PRs are meant to be review by other developers, mainly wasabiz and should be merged by other developers after review. Following such procedure on each small bugfix is cumbersome so we directly push to master.
If you want to PR to trigger CI, it's not a problem. Then please distinguish trigger only PR and review wanting PR.

**Comment by omasanori** [comment]
OK.

**Pull request merged**
