### PR TITLE
WIP: Add (picrin socket) and (srfi 106).

### PR DESCRIPTION
**Pull request by omasanori**
**Do not merge this PR until all tasks has been addressed.**

I need socket support in picrin, so I began to write a binding. However, I'm not sure whether my usage of API and coding style is correct. Thus, I'd make a RFC PR with a part of the binding. Would you review me before I write rest of the socket binding? Any suggestions are welcome.

Also, let me know if anyone already wrote and published a socket binding.

Tasks:
* [x] Implement SRFI 106 completely
* [x] Add tests which don't need actual connection
* [x] Add tests with actual connection (mostly done)
* [x] Ask someone about edge cases and ambiguity of SRFI 106
* [x] Run tests on some non-Linux platforms (FreeBSD? OSX?)

### CODE REVIEW

**Comment by omasanori** [comment]
hmm... [a CI build](https://travis-ci.org/picrin-scheme/picrin/jobs/65229190) fails in the debug build but not the release build, only on `gcc -m64`.

**Comment by omasanori** [comment]
I've confirmed that all tests are passed on Linux (x86, amd64) and FreeBSD (amd64).

**Comment by omasanori** [comment]
Probably it runs on OS X (need tests). Some tests failed on Cygwin (maybe caused by Windows Firewall).

AFAIK it causes a build failure on MSVC, MinGW (need Winsock 2 support), Solaris and illumos (on those platforms, linking with libnsl and libsocket is needed to use sockets in a program).

**Comment by omasanori** [comment]
Would you review the PR for merging? I'd like to leave some platforms unsupported for now since some other modules also can't be built on them.

**Comment by wasabiz** [comment]
Okay, I'll take a look at the request.

2015年6月19日(金) 17:36 OGINO Masanori <notifications@github.com>:

**Comment by wasabiz** [comment]
@omasanori 

Hi, I'm back :) Looking over the commits, my guess is that we may move socket.scm and socket.c to under contrib/srfi directory. Current design of (picrin socket) library appears to be highly affected by the design of srfi 104 and I couldn't find reasons to split (picrin socket) library and (srfi 104). By integrating them we would be able to avoid difficulties in writing generic scheme code resulting from divergence of libraries provided by scheme interpreters. How does it sound to you? I want to get your feedback. If you found something I may have missed please let me know.

**Comment by omasanori** [comment]
> Current design of (picrin socket) library appears to be highly affected
by the design of srfi 104 and I couldn't find reasons to split (picrin
socket) library and (srfi 104).

Sure. How can I integrate them? I created (picrin socket) internal library
because I don't know how to declare C code and scheme code as the same
library. Also, are symbols resolved correctly on such situations?

Perhaps the integration also requires some modifications since r7rs and
optional are the same order.

**Comment by wasabiz** [comment]
@omasanori 

> How can I integrate them?

Contrib/r7rs will help you understand how to use both c and scheme in a nitro.
Technically, picrin executes all pic_init_CONTRIBNAME(pic); first and then evaluates all scheme symbols. You mustn't use procedures or macros defined in scheme when you write pic_init_socket but you can use any procedures defined in c when you write scheme code!

> Perhaps the integration also requires some modifications since r7rs and
optional are the same order.

The numbering is almost shit (for historical reasons). They have not been refactored since we have a plan to introduce an algorithmic dependency resolver. I'll reorder them now!

**Comment by omasanori** [comment]
OK, now optional is after r7rs, so I'll remove the dependency from socket.scm to merge to r7rs.

**Comment by omasanori** [comment]
Wait, I was so careless last night. The important is the order of **srfi** and optional. I'm sorry.

**Comment by omasanori** [comment]
Done!

**Comment by omasanori** [comment]
Is it rejected?

**Comment by wasabiz** [comment]
wow that's mistake!

**Comment by omasanori** [comment]
Thanks :smiley:

**Pull request merged**
