### PR TITLE
print logo before starting repl

### PR DESCRIPTION
**Pull request by KeenS**
The logo(?) is generated by `figlet` command.

Just for fun

### CODE REVIEW

**Comment by wasabiz** [comment]
Cool. But I want to turn this on by giving an option like "-i" (for interactive) or something. I'd like to keep the default simple.

**Comment by KeenS** [comment]
Even though the logo is printed only when entering interactive REPL? Then, I'll withdraw this PR. I don't think there are someone who bother to print logo with giving a special option.

**Comment by wasabiz** [comment]
@KeenS 

Sometimes I prefer simple and sometimes prefer gorgeous. It'd be nice if the repl shows the logo and some usage especially for new people. I think just discarding the patch is somehow mottainai.

**Comment by KeenS** [comment]
Hmm. Then I'd like to have version info, build date, and so on.
Current picrin has no REPL commands so there are few thing to print.
Current: Logo, Web Page, How to quit the REPL(`^D`).

**Pull request closed without merging**
